<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>1673208d-6460-4944-aff7-0e12d70e156b</elementGuidId>
    <imagePath></imagePath>
    <name>input_combo_box_demo</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/form[1]/div[1]/div[2]/div[1]/div[1]/input[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>#combo-box-demo</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@id,'combo-box-demo') and equals(@class,'MuiInputBase-input MuiOutlinedInput-input MuiInputBase-inputAdornedEnd MuiAutocomplete-input MuiAutocomplete-inputFocused css-1563wdh')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>MuiInputBase-input MuiOutlinedInput-input MuiInputBase-inputAdornedEnd MuiAutocomplete-input MuiAutocomplete-inputFocused css-1563wdh</value>
        <webElementGuid>68f2f4d8-3a8b-4c68-8bdd-638a9b823a0c</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>combo-box-demo</value>
        <webElementGuid>ad81639a-16d4-4a47-a2e6-2b19b969bbd2</webElementGuid>
    </webElementProperties>
</WebElementEntity>